apiVersion: v1
kind: Secret
metadata:
  name: cloudpulse-secrets
  namespace: cloudpulse
type: Opaque
data:
  # Add your secrets here in base64 encode form, not in plain text
  DATABASE_URL:
  REDIS_URL: 
  SPACES_SECRET_ACCESS_KEY: 
  JWT_SECRET: 