apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudpulse-worker
  labels:
    app: worker
  namespace: cloudpulse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: registry.digitalocean.com/cloudpulse-registry/worker:${APP_VERSION}
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: cloudpulse-secrets
            - configMapRef:
                name: cloudpulse-config
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
